/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gpoi.test;

import jssc.SerialPortList;

public class App {
    public static void main(String[] args) {
        for (String name : SerialPortList.getPortNames()) {
            System.out.println(name);
        }
    }
}
